### ISSUE TITLE
Bower not working

### ISSUE THREAD

**Issue by juanneilson** [xch89820/Chart.Funnel.js#3]
Hi there

Thank you for your plugin. I think bower install it's not working with it. I'm trying:
bower install chartjs-funnel --save

And it says 'don't found'

**Comment by jp-loudcanvas** [comment]
Me too. But at this time, with Bower you can use:
"Chart.Funnel.js"  
like:
"Chart.Funnel.js":"~1.0.4"

**Comment by xch89820** [comment]
Already update to bower
